---
parent: csdk
serviceName: csdk-browser-example
language: nodejs
build:
    nodejs:
        outputDistDir: csdk
        command: |
            mkdir csdk
            cp example.html csdk/
            cp -r webApp-plivo/public/img csdk/
            cp -r webApp-plivo/public/js csdk/
            cp -r webApp-plivo/public/lib csdk/
            cp -r webApp-plivo/public/css csdk/
